#!/bin/bash

# Get current GTK theme
theme=$(gsettings get org.gnome.desktop.interface gtk-theme)

# Define your Pywal color scheme paths
dark_theme="$HOME/.cache/wal/colors-rofi-dark.rasi"
light_theme="$HOME/.cache/wal/colors-rofi-light.rasi"
rofi_theme="$HOME/.config/rofi/colors.rasi"

# Strip quotes from theme name
ln -sf "$dark_theme" "$rofi_theme"

# Reload Rofi to apply the changes
# rofi -reload
