#!/bin/bash

# Path to store the current theme state
theme_state_file="$HOME/.cache/current_gtk_theme"

# Initialize the state file if it doesn't exist
if [ ! -f "$theme_state_file" ]; then
  touch "$theme_state_file"
  echo "unknown" >"$theme_state_file"
fi

# Continuous monitoring loop
while true; do
  # Get the current GTK theme
  current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme)

  # Read the previous theme from the state file
  previous_theme=$(cat "$theme_state_file")

  # Determine if the theme has changed
  if [[ $current_theme != $previous_theme ]]; then
    if [[ $current_theme == *"dark"* ]]; then
      notify-send "Dark theme is active."
      plasma-apply-colorscheme MaterialYouDark
    else
      notify-send "Light theme is active."
      plasma-apply-colorscheme MaterialYouLight
    fi
    # Update the state file with the new theme
    echo "$current_theme" >"$theme_state_file"
  fi

  # Sleep for a minute before checking again
  sleep 10
done
