#!/bin/bash

# Path to the temporary file for storing the last known wallpaper path
cache_dir="$HOME/.cache"
temp_file="$cache_dir/last_wallpaper_path"

# Create the .cache directory if it doesn't exist
mkdir -p $cache_dir

# Initialize the temporary file if it doesn't exist
if [ ! -f $temp_file ]; then
    swww query | awk -F 'image: ' '{print $2}' > $temp_file
fi

while true; do
    # Retrieve the current wallpaper path
    current_wallpaper=$(swww query | awk -F 'image: ' '{print $2}')

    # Check if the wallpaper path has changed
    if [ "$(cat $temp_file)" != "$current_wallpaper" ]; then
        # Run your script here
        ~/.config/hypr/scripts/wallpaper

        # Update the temporary file with the new wallpaper path
        echo $current_wallpaper > $temp_file
    fi

    # Sleep for a few seconds before checking again
    sleep 10
done

