#!/bin/bash

# Define formatting variables
GREEN='\033[1;32m'
NC='\033[0m' # No Color
GLYPH='󰏘'
# Genereting Wal color 

echo -e "\n${GREEN}${GLYPH} Genereting Pywal colors.${NC}"
wal -i $(swww query | awk -F 'image: ' '{print $2}')

# Directory containing PNG files
icon_dir="$HOME/.config/hypr/scripts/icons/"

echo -e "${GREEN}${GLYPH} Choosing a random PNG icon from $icon_dir...${NC}"

# Get a list of PNG files starting with "pywal-"
icons=("$icon_dir"pywal-*.png)

# Check if there are PNG files
if [ ${#icons[@]} -eq 0 ]; then
    echo -e "${GREEN}${GLYPH} Error: No PNG files found in $icon_dir${NC}"
    exit 1
fi

# Choose a random icon
random_index=$(( RANDOM % ${#icons[@]} ))
icon=${icons[$random_index]}
echo -e "${GREEN}${GLYPH} Selected icon: $icon${NC}"

# Notification details
title="Changing system colors"
message="New colors goes brrr!"

# Path to palette.png
palette_icon="$icon_dir/palette.png"

# Check if palette.png exists
if [ ! -f "$palette_icon" ]; then
    echo -e "${GREEN}${GLYPH} Error: palette.png not found in $icon_dir${NC}"
    exit 1
fi

echo -e "${GREEN}${GLYPH} Sending notification with icon: $palette_icon${NC}"

# Send the notification with palette.png as the icon
notify-send -i "$palette_icon" -e -h string:x-canonical-private-synchronous:sys-notify -u low -t 2800 "$title" "$message"

# Execute other commands

echo -e "\n${GREEN}${GLYPH} Changing icons color ${NC}"
python ~/.config/hypr/scripts/icons-colors.py

echo -e "\n${GREEN}${GLYPH} Running colors script (for hyprlock, lock screen) ${NC}"
~/.config/hypr/scripts/colors

echo -e "\n${GREEN}${GLYPH} Aplying hyprland colors (for window borders) ${NC}"
python3 ~/.config/hypr/scripts/colors-hypr.py

echo -e "\n${GREEN}${GLYPH} Running colors-folders.py (for papirus colored folders).${NC}"
python ~/.config/hypr/scripts/colors-folders.py

echo -e "\n${GREEN}${GLYPH} Building Qt theme with script build-qt ${NC}"
~/.config/hypr/scripts/build-qt
~/.config/hypr/scripts/build-qt6 

echo -e "\n${GREEN}${GLYPH} Building kvuntum theme with script build-kvuntum ${NC}"
python ~/.config/hypr/scripts/build-kvantum.py

echo -e "\n${GREEN}${GLYPH} Running walogram (for telegram) ${NC}"
walogram -s

echo -e "\n${GREEN}${GLYPH} Running pywal-discord (for discord) ${NC}"
pywal-discord

echo -e "\n${GREEN}${GLYPH} Running zed-theme (for Zed) ${NC}"
~/.config/hypr/scripts/zed-theme

echo -e "\n${GREEN}${GLYPH} Script execution completed.${NC}"

# Randomly decide whether to show the "Did you notice?" notification
show_notice=$(( RANDOM % 5 ))  # 20% chance

if [ $show_notice -eq 0 ]; then
    # Choose a new random icon
    random_index=$(( RANDOM % ${#icons[@]} ))
    icon=${icons[$random_index]}
    echo -e "${GREEN}${GLYPH} Sending 'Did you notice?' notification with icon: $icon${NC}"
    notify-send -i "$icon" -e -h string:x-canonical-private-synchronous:sys-notify -u low -t 10000 "Did you notice?" "The notification icon has changed!"
fi
